services:
    sonata.admin.category:
        class: Wrd\Bundle\LegoBundle\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Lego", label: "Category" }
        arguments:
            - ~
            - Wrd\Bundle\LegoBundle\Entity\Category
            - ~
        calls:
            - [ setTranslationDomain, [WrdLegoBundle]]

    sonata.admin.product:
            class: Wrd\Bundle\LegoBundle\Admin\ProductAdmin
            tags:
                - { name: sonata.admin, manager_type: orm, group: "Lego", label: "Product" }
            arguments:
                - ~
                - Wrd\Bundle\LegoBundle\Entity\Product
                - ~
            calls:
                - [ setTranslationDomain, [WrdLegoBundle]]