parameters:
#    wrd_lego.example.class: Wrd\Bundle\LegoBundle\Example

services:
    wrd_user.registration.form.type:
            class: Wrd\Bundle\LegoBundle\Form\Type\RegistrationFormType
            arguments: [%fos_user.model.user.class%]
            tags:
                - { name: form.type, alias: wrd_user_registration }